// <auto-generated />
namespace Thinktecture.IdentityServer.Core.Repositories.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddIDKeyToIdentityProvider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIDKeyToIdentityProvider));
        
        string IMigrationMetadata.Id
        {
            get { return "201210232018407_AddIDKeyToIdentityProvider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
