// <auto-generated />
namespace Thinktecture.IdentityServer.Core.Repositories.Migrations.SqlCe
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RPTokenType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RPTokenType));
        
        string IMigrationMetadata.Id
        {
            get { return "201307221954069_RPTokenType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
