//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.IdentityServer.Resources.Models
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Client {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Client() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thinktecture.IdentityServer.Resources.Models.Client", typeof(Client).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Code Flow.
        /// </summary>
        public static string AllowCodeFlow {
            get {
                return ResourceManager.GetString("AllowCodeFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow code flow..
        /// </summary>
        public static string AllowCodeFlowDescription {
            get {
                return ResourceManager.GetString("AllowCodeFlowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Implicit Flow.
        /// </summary>
        public static string AllowImplicitFlow {
            get {
                return ResourceManager.GetString("AllowImplicitFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow implicit flow..
        /// </summary>
        public static string AllowImplicitFlowDescription {
            get {
                return ResourceManager.GetString("AllowImplicitFlowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Refresh Tokens.
        /// </summary>
        public static string AllowRefreshToken {
            get {
                return ResourceManager.GetString("AllowRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Refresh Tokens. This enabled offline access for the client to the resource..
        /// </summary>
        public static string AllowRefreshTokenDescription {
            get {
                return ResourceManager.GetString("AllowRefreshTokenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Resource Owner Flow.
        /// </summary>
        public static string AllowResourceOwnerFlow {
            get {
                return ResourceManager.GetString("AllowResourceOwnerFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Resource Owner Flow..
        /// </summary>
        public static string AllowResourceOwnerFlowDescription {
            get {
                return ResourceManager.GetString("AllowResourceOwnerFlowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID..
        /// </summary>
        public static string ClientIdDescription {
            get {
                return ResourceManager.GetString("ClientIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret.
        /// </summary>
        public static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret..
        /// </summary>
        public static string ClientSecretDescription {
            get {
                return ResourceManager.GetString("ClientSecretDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret is required for Code and Resource Owner Flows..
        /// </summary>
        public static string ClientSecretRequiredError {
            get {
                return ResourceManager.GetString("ClientSecretRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description..
        /// </summary>
        public static string DescriptionDescription {
            get {
                return ResourceManager.GetString("DescriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name..
        /// </summary>
        public static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URI.
        /// </summary>
        public static string RedirectUri {
            get {
                return ResourceManager.GetString("RedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URI..
        /// </summary>
        public static string RedirectUriDescription {
            get {
                return ResourceManager.GetString("RedirectUriDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URI must be HTTPS..
        /// </summary>
        public static string RedirectUriMustBeHTTPS {
            get {
                return ResourceManager.GetString("RedirectUriMustBeHTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URI is required for Code and Implicit Flows..
        /// </summary>
        public static string RedirectUriRequiredError {
            get {
                return ResourceManager.GetString("RedirectUriRequiredError", resourceCulture);
            }
        }
    }
}
