//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.IdentityServer.Resources.Models
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RelyingParty {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RelyingParty() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thinktecture.IdentityServer.Resources.Models.RelyingParty", typeof(RelyingParty).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable this RP..
        /// </summary>
        public static string EnabledDescription {
            get {
                return ResourceManager.GetString("EnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting Certificate.
        /// </summary>
        public static string EncryptingCertificate {
            get {
                return ResourceManager.GetString("EncryptingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional X.509 certificate to encrypt outgoing tokens..
        /// </summary>
        public static string EncryptingCertificateDescription {
            get {
                return ResourceManager.GetString("EncryptingCertificateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting Certificate Thumbprint.
        /// </summary>
        public static string EncryptingCertificateThumbprint {
            get {
                return ResourceManager.GetString("EncryptingCertificateThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting Certificate Thumbprint.
        /// </summary>
        public static string EncryptingCertificateThumbprintDescription {
            get {
                return ResourceManager.GetString("EncryptingCertificateThumbprintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Data 1.
        /// </summary>
        public static string ExtraData1 {
            get {
                return ResourceManager.GetString("ExtraData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra data you can associate with the RP. (1).
        /// </summary>
        public static string ExtraData1Description {
            get {
                return ResourceManager.GetString("ExtraData1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Data 2.
        /// </summary>
        public static string ExtraData2 {
            get {
                return ResourceManager.GetString("ExtraData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra data you can associate with the RP. (2).
        /// </summary>
        public static string ExtraData2Description {
            get {
                return ResourceManager.GetString("ExtraData2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Data 3.
        /// </summary>
        public static string ExtraData3 {
            get {
                return ResourceManager.GetString("ExtraData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra data you can associate with the RP. (3).
        /// </summary>
        public static string ExtraData3Description {
            get {
                return ResourceManager.GetString("ExtraData3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptive name (shows up in trace logs)..
        /// </summary>
        public static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm/Scope Name.
        /// </summary>
        public static string Realm {
            get {
                return ResourceManager.GetString("Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm/Scope identifier URI..
        /// </summary>
        public static string RealmDescription {
            get {
                return ResourceManager.GetString("RealmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URL.
        /// </summary>
        public static string ReplyTo {
            get {
                return ResourceManager.GetString("ReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to return (ReplyTo parameter) to once a token is issued..
        /// </summary>
        public static string ReplyToDescription {
            get {
                return ResourceManager.GetString("ReplyToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetric Signing Key.
        /// </summary>
        public static string SymmetricSigningKey {
            get {
                return ResourceManager.GetString("SymmetricSigningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 encoded key used for symmetric signing of tokens..
        /// </summary>
        public static string SymmetricSigningKeyDescription {
            get {
                return ResourceManager.GetString("SymmetricSigningKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token life time (in minutes).
        /// </summary>
        public static string TokenLifeTime {
            get {
                return ResourceManager.GetString("TokenLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be used to override the default token lifetime (a value of 0 uses the global default)..
        /// </summary>
        public static string TokenLifeTimeDescription {
            get {
                return ResourceManager.GetString("TokenLifeTimeDescription", resourceCulture);
            }
        }
    }
}
