//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.IdentityServer.Web.App_LocalResources.OidcAuthorize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Consent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Consent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thinktecture.IdentityServer.Web.App_LocalResources.OidcAuthorize.Consent", typeof(Consent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal address.
        /// </summary>
        public static string Scope_address_desc {
            get {
                return ResourceManager.GetString("Scope_address_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Scope_address_label {
            get {
                return ResourceManager.GetString("Scope_address_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Scope_email_desc {
            get {
                return ResourceManager.GetString("Scope_email_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Scope_email_label {
            get {
                return ResourceManager.GetString("Scope_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this information even when you are offline.
        /// </summary>
        public static string Scope_offline_desc {
            get {
                return ResourceManager.GetString("Scope_offline_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Access.
        /// </summary>
        public static string Scope_offline_label {
            get {
                return ResourceManager.GetString("Scope_offline_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Scope_phone_desc {
            get {
                return ResourceManager.GetString("Scope_phone_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Scope_phone_label {
            get {
                return ResourceManager.GetString("Scope_phone_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, Gender, Picture, Date of Birth, Website, Location.
        /// </summary>
        public static string Scope_profile_desc {
            get {
                return ResourceManager.GetString("Scope_profile_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Profile.
        /// </summary>
        public static string Scope_profile_label {
            get {
                return ResourceManager.GetString("Scope_profile_label", resourceCulture);
            }
        }
    }
}
